version: "3.1"
services:
  backend-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app/
      - /app/node_modules
    networks:
      - backend-server-network

  prometheus-server:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    networks:
      - backend-server-network
    volumes:
      - prometheus-storage:/etc/prometheus

  grafana-server:
    image: grafana/grafana:latest
    ports:
      - 3001:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - backend-server-network

volumes:
  prometheus-storage:
  grafana-storage:

networks:
  backend-server-network:
    driver: bridge
